### ISSUE TITLE
Attachment Image

### ISSUE THREAD

**Issue by edwin-candinegara** [DroidCare/dc#5]
@kenrick95 : the Android application will send the image as a String of Base 64 Encoded image Bitmap. Please store the encoded bitmap to the database directly.

If there is any request on an attachment image, the response should be the encoded image bitmap string from the database.

Thanks!

**Comment by kenrick95** [comment]
Done per 1a3a8b9d5fa90bd8e98b767f2d96b797725a25cf

:grin:

**Comment by edwin-candinegara** [comment]
Ok. Thanks!
