### ISSUE TITLE
User Details

### ISSUE THREAD

**Issue by edwin-candinegara** [DroidCare/dc#6]
User details now will include Notification Type as well. There are 2 types: SMS and/or Email.

The data sent to the PHP server will be an integer with the following agreement:
- 1 = SMS notification only
- 2 = Email notification only
- 3 = SMS & Email notification

By default, there will be a local notification managed by the Android application.
Thanks!

**Comment by kenrick95** [comment]
Why not do enum so that it has more meaning when seen in database

My suggestion is: `enum('sms', 'email', 'all')`

How

**Comment by kenrick95** [comment]
previous_id not be NULL

**Comment by kenrick95** [comment]
Done per 0dedc4946e18fc9732a4f31ef216e0de5d4772ad
